name: citric
description: Adicionar biblioteca Citric para React Stack

types:
  - app

# Nome com formatação livre que será exibido no portal.
display-name: Citric
# caso a picture esteja fora do repo colocar uma url externa
# Categorias disponíveis:
# [sre, frontend, backend, fullStack, analytics]
picture: "logo.png"
# Especificar a categoria da stack.
# Plugin podem perceber a qualquer category
category: Frontend
## Lista de tecnologias que você gostaria de enfatizar que é compativel
compatibility:
  - Typescript
# tecnologies que o plugin utiliza
# A lista completa das tecnologias que podem ser cadastradas estão disponiveis na Documentação
technologies: ["Typescript"]
